

document.addEventListener('DOMContentLoaded', function() {
 // Selecting elements
    const colorBox = document.getElementById('color-box');
    const changeColorBtn = document.getElementById('change-color-btn');

    // Function that generates a random color
    function getRandomColor(hexaColor) {
 var letters = '0123456789ABCDEF';
        var color = '#';
        for (var i = 0; i < hexaColor.length; i++) {
            color += letters[Math.floor(Math.random() * 16)];
 }
        return color;
    }

   // Event listener on change-color-btn element 
   changeColorBtn.addEventListener('click', function() {
       // Changing background color of the color to a random generated by getRandomColor()
       colorBox.style.backgroundColor = getRandomColor();
   });
});


  